### ISSUE TITLE
Fails to install as NPM module with NPM (works with Yarn)

### ISSUE THREAD

**Issue by ro-tex** [wparad/aws-architect.js#19]
Steps:
 - add as dependency to a project
 - run `npm install` within that project

Output:
```
npm ERR! path /home/vagrant/source/comment-service/node_modules/error-object-polyfill/bin/aws-architect.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/vagrant/source/comment-service/node_modules/error-object-polyfill/bin/aws-architect.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-07-10T10_51_26_976Z-debug.log
```

Environment:
 - OS: MacOS, Linux (Ubuntu 18.04 LTS)
 - Node Version: 8.10
 - NPM Version: 5.6.0, 5.10.0, 6.1.0

**Comment by wparad** [comment]
This is actually a problem with the `error-object-polyfill` library.  I've released version 1.0.13 which fixes it.
But because of the bug it was making it seem like this library.  To resolve:
* remove/wait for [this PR](https://github.com/Cimpress-MCP/microservice-utilities.js/pull/11) to be merged
AND
* Update the `error-object-polyfill` version to `1.0.13`
